""" vundle - plugins settings
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" alternatively, pass a path where Vundle should install plugins
"let path = '~/some/path/here'
"call vundle#rc(path)

" let Vundle manage Vundle, required
Plugin 'gmarik/vundle'

" Plugins:
Plugin 'Valloric/YouCompleteMe'

let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'
let g:ycm_path_to_python_interpreter = '/usr/bin/python'

filetype plugin indent on     " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Plugin commands are not allowed.
" Put your stuff after this line

syntax on    	        " 語法上色

set mouse=a
set encoding=utf-8

set number 	            " 顯示行號
set ruler 	            " 顯示右下角詳細資訊
set cindent 	        " 自動縮排 
set cursorline 	        " 底線 目前游標位置
set expandtab  	        " 將文件中的tab轉成space顯示
set tabstop=4 	        " tab換成幾個空格
set shiftwidth=4        " 自動縮排時的空格數量

inoremap ( ()<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i
inoremap [ []<Esc>i
inoremap {<CR> {<CR>}<Esc>ko
inoremap {{ {}<ESC>i

""" COLOR settings
set background=dark
colorscheme Tomorrow-Night-Bright 
"colorscheme kolor 
"colorscheme molokai
"colorscheme solarized


