# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load Antigen
source ~/.zsh/antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh)
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

# Some more bundles from zsh-users
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting

# autojump
antigen bundle autojump

# Load the theme.
antigen theme romkatv/powerlevel10k
#antigen theme agnoster
#antigen theme robbyrussell
#antigen theme ys

# Tell Antigen that you're done.
antigen apply

### PATH
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:$HOME/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:$PATH

### For powerlevel10k theme 
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Load .aliases
source ~/.aliases

### For powerline
export POWERLINE_COMMAND=powerline
export POWERLINE_CONFIG_COMMAND=powerline-config
 #. $HOME/.local/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh

### For nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

### For Conda 
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/tslsun/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/tslsun/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/tslsun/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/tslsun/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<

### For vi-mode
bindkey -v
